application: snapmecatz
version: 1
runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /Styles
  static_dir: Styles
 
- url: /.*
  script: main1.py

libraries:
- name: pycrypto
  version: "2.6"